### ISSUE TITLE
Support For Unique Enums

### ISSUE THREAD

**Issue by iway1** [iway1/react-ts-form#10]
Right now it isn't possible to have a unique enum field that works in any useful way.

I think the only way to implement this would be creating a new function specifically for creating unique enum fields, something like:

```tsx
const RadioSchema = createUniqueEnumField('id');

const MyForm = z.object({
  radio: MyUniqueEnum.enum(["one", "two"])
})
```

Needs to be able to pass in options at the form level and only be passed to the mapping once per field component type.

**Comment by iway1** [comment]
Alternatively, might remove the enum values feature altogether. Seems to be causing a lot of confusion and may be a footgun, even though it sounds really cool on paper.

**Comment by scamden** [comment]
wait could you explain more about this decision? i would definitely want to define the possible options in the schema not in the component usage..
