### ISSUE TITLE
issue: npm ERR Could not resolve dependency

### ISSUE THREAD

**Issue by ingadi** [iway1/react-ts-form#105]
### Version Number

1.6.3

### Steps to reproduce

1. npm install @ts-react/form
2. npm install react-hook-form @hookform/resolvers
3. npm update

### Expected behaviour

No npm Errors.

### Relevant log output

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bulletproof-react-vite@0.0.0
npm ERR! Found: @hookform/resolvers@3.1.0
npm ERR! node_modules/@hookform/resolvers
npm ERR!   @hookform/resolvers@"^3.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @hookform/resolvers@"^2.8.0" from @ts-react/form@1.6.3
npm ERR! node_modules/@ts-react/form
npm ERR!   @ts-react/form@"^1.6.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by ingadi** [comment]
Skipping installing `@hookform/resolvers` doesn't seem to affect my forms so that's how I'm getting around this.

**Comment by iway1** [comment]
think we just need to update the package.json to work with the new version of hookform resolvers

**Comment by christopher-kapic** [comment]
I think this problem is back. I created [this PR](https://github.com/iway1/react-ts-form/pull/148) to resolve it.
