### ISSUE TITLE
Typesafe props not working for field that is nullable.optional or .nullish

### ISSUE THREAD

**Issue by iffa** [iway1/react-ts-form#110]
Prop types seems to break when optional/nullable/nullish are not in the correct order. See the reprodcution below

TL;DR:

- `optional().nullable()` works
- `nullable().optional()` does not
- `nullish()` does not, as it is equivalent to `nullable().optional()`

```tsx
import { TextInput } from "@mantine/core";
import { createTsForm, useTsController } from "@ts-react/form";
import { z } from "zod";

const TextField = ({ description }: { description?: string }) => {
  const { field, error } = useTsController<string>();

  return (
    <TextInput
      value={field.value}
      onChange={(e) => field.onChange(e.target.value)}
      label={field.name}
      placeholder={description}
      error={error?.errorMessage}
    />
  );
};

const mapping = [[z.string(), TextField]] as const;

export const Form = createTsForm(mapping);

export const MyFormComponent = () => {
  return (
    <Form
      schema={z.object({
        displayNameOptionalNullable: z.string().optional().nullable(),
        displayNameNullableOptional: z.string().nullable().optional(),
        displayNameNullish: z.string().nullish(),
      })}
      props={{
        displayNameOptionalNullable: {
          // Works, no TS errors
          description: "",
        },
        displayNameNullableOptional: {
          // Does not work, Type '{ description: string; }' is not assignable to type 'undefined'
          description: "",
        },
        displayNameNullish: {
          // Does not work, Type '{ description: string; }' is not assignable to type 'undefined'
          description: "",
        },
      }}
      onSubmit={() => {
        /* ... */
      }}
    />
  );
};
```

**Comment by iway1** [comment]
got a fix just seeing if I can get a review on it

**Comment by davevilela** [comment]
I think this is still an issue on the latest version.

![Screenshot 2023-09-22 at 12 34 45](https://github.com/iway1/react-ts-form/assets/18126630/7401416d-e1d0-4b6b-8d98-432abd29c759)

**Comment by davevilela** [comment]
Something interesting: It happens when my field type is wrapped in `createUniqueFieldSchema`

**Comment by davevilela** [comment]
Update: optional().unwrap() works fine

**Comment by scamden** [comment]
> Something interesting: It happens when my field type is wrapped in `createUniqueFieldSchema`

Ah interesting, maybe we are failing to unwrap properly when branded (which createUniqueSchema uses under the hood). Lets create a new issue for that since it's a different problem technically. (Feel free to make a PR with a failing "type" test as well. See the tests in the PR that closed this issue for reference)

**Comment by j1mie** [comment]
Experiencing the same issue with `createUniqueFieldSchema`, props and optional fields

**Comment by iStorry** [comment]
Any update on this?

**Comment by kanapan** [comment]
Has anyone solved this issue or found a temporary workaround?
