### ISSUE TITLE
New Functionality - useDateFieldInfo()

### ISSUE THREAD

**Issue by bartoszgolebiowski** [iway1/react-ts-form#114]
I have implemented a new functionality in the project that introduces a feature similar to the existing `useStringFieldInfo()` function. The new function is called `useDateFieldInfo()`. It provides essential information and utilities for handling date fields within the project.

**Comment by bartoszgolebiowski** [comment]
https://github.com/iway1/react-ts-form/pull/115

**Comment by iway1** [comment]
merged and released
