### ISSUE TITLE
Any recommendations for libraries similar to react-ts-form?

### ISSUE THREAD

**Issue by kanapan** [iway1/react-ts-form#146]
Hi,

I've been exploring form libraries and found react-ts-form, which I find very useful for type-safe and declarative form handling. However, it seems like the library is no longer being actively maintained.

I’m looking for other libraries with similar features or functionality that are actively supported. If you have any recommendations or experiences with such libraries, I’d greatly appreciate your input.

Thank you!

**Comment by tordans** [comment]
Which did you find and evaluate @kanapan?
