### ISSUE TITLE
issue: Zod infer not working with createUniqueFieldSchema

### ISSUE THREAD

**Issue by lucasjungdeveloper** [iway1/react-ts-form#32]
### Version Number
1.0.10

![image](https://user-images.githubusercontent.com/60625831/211680546-c565f47d-7f2d-4dd6-909c-9ab69926e610.png)
When infering the type returned by the createUniqueFieldSchema function shows any instead of number

**Comment by iway1** [comment]
Hmm that's pretty weird b/c NumberSchema is just a zod type. - I am able to reproduce this locally though, checking it out now

**Comment by iway1** [comment]
Fixed in #40
