### ISSUE TITLE
Quick placeholders can't contain "//"

### ISSUE THREAD

**Issue by florian-lefebvre** [iway1/react-ts-form#39]
### Version Number

^1.0.10

### Steps to reproduce

1. Create a schema like the following and pass it to the form

```ts
const schema = z.object({
    url: z.string().describe('URL // https://google.com'),
})
```

### Expected behaviour

The placeholder should be `https://google.com` but it's only `https:`. I guess this is because the separator is `//` and so the label is `segments[0]` and the placeholder `segments[1]`.

**Comment by iway1** [comment]
Hmm good point, yeah right now it just looks for `//` so would need to change it.

Wondering what a good symbol would be that would be less likely to have conflicts

**Comment by florian-lefebvre** [comment]
It could be useful to make it configurable in the options of createTsForm https://github.com/iway1/react-ts-form/blob/main/src/createSchemaForm.tsx#L163

**Comment by iway1** [comment]
yeah good idea that way it wouldn't be a breaking change as well

**Comment by florian-lefebvre** [comment]
But I think changing the default one would be useful, urls are often used as placeholder

**Comment by iway1** [comment]
good point, we'll change the default. What about `--` as the separator? Seems pretty unlikely to have conflicts

gonna have to be in v2 since it's breaking though

**Comment by florian-lefebvre** [comment]
LGTM

**Comment by earlyaugust2** [comment]
I ran into this problem as well

**Comment by lucasjungdeveloper** [comment]
I think the default could stay as it is if it checks for `' // '` instead of `'//'`
Since in the URL it won't be surrounded by spaces
And by doing so it woudn't be a breaking change

**Comment by florian-lefebvre** [comment]
Yeah sounds great! And to prevent errors we could do

```ts
const [label, ...rest] = describe.split(' // ')
const placeholder = rest.join(' // ')
```
