### ISSUE TITLE
ZodEffects support

### ISSUE THREAD

**Issue by iway1** [iway1/react-ts-form#72]
Library doesn't support `.transform` on schemas currently:

```tsx
const mapping = [[z.string(), TextField]] as const;

const Form = createTsForm(mapping);

const FormSchema = z.object({textField: z.string().tranform(v=>parseInt(v));

<Form schema={FormSchema} /> // Errors no found schema
```

Would be nice to be able to transform / preprocess stuff in the schema and still have it match the schema.

**Comment by nkalpak** [comment]
Here's a [type for this](https://github.com/nkalpak/zodform/blob/main/apps/core/src/core/extract-schema-from-effects.ts) in case you need it :))

**Comment by iway1** [comment]
@nkalpak nice thanks!

**Comment by iway1** [comment]
going to close for now because we can't support this without ejecting from RHF, but do want to add it in 2.0

**Comment by scamden** [comment]
fwiw, we are running into the desire for this as well
