### ISSUE TITLE
Form prop in FormContainer not available.

When passing a react-hook-form form to the FormContainer, the form property is not available. This is making the library difficult to use, becuase its hard to access the submitting value of the form.

### ISSUE THREAD

**Issue by acollazomayer** [iway1/react-ts-form#87]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iway1** [comment]
good point, form prop should be available in the FormContainer. Should be easy to add this.

Just to make sure I understand, you mean the return from useForm?

```tsx
const form = useForm() // 👈
```

**Comment by iway1** [comment]
Actually - You should be able to use `react-hook-form`'s `useFormContext()` already:

```tsx
function FormContainer({children, onSubmit}:{children: ReactNode, onSubmit: ()=>void}) {
  const form = useFormContext();
}
```

I think we'll just update the documentation to make this more obvious

**Comment by iway1** [comment]
gonna close, if the above solution didn't work let me know

**Comment by acollazomayer** [comment]
@iway1 Did you check this, can you please show examples on how to handle async submissions. Because I am not able to make this work.
