### ISSUE TITLE
Lower required version of React in peerDependencies

### ISSUE THREAD

**Issue by antcar112** [iway1/react-ts-form#93]
I'm wondering if it would be possible to lower the support versions of React in the peerDependencies. I would love to use the library, but my team is currently forced to use React 17, so installing requires us to use `overrides` in each project we want to add it to. It would be nice not to have to do this if possible.

If there's no concerns, I'm happy to open a PR to change this to match the range currently supported by `react-hook-form` (`"^16.8.0 || ^17 || ^18"`) https://github.com/react-hook-form/react-hook-form/blob/master/package.json#L122

**Comment by iway1** [comment]
I don't see any reason why not :)
